---
title: "annotate"
format: html
editor: visual
editor_options: 
  chunk_output_type: console
---

# [**Understand annotate() to improve your plots**](https://www.youtube.com/watch?v=RfdcjMP2qMM&list=LL&index=2)

```{r}
library(tidyverse)
```

```{r}
scatterplot <- palmerpenguins::penguins |> 
  filter(!is.na(sex)) |> 
  ggplot(aes(x = bill_length_mm, flipper_length_mm, color = species )) + 
  geom_point(size = 2.5) + 
  labs( 
    x = "Bill length (in mm)", 
    y = "Flipper length (in mm)", 
    color = "Species", 
    title = "Measurement of different Penguin Species") + 
  theme_minimal(base_size = 16) + 
  theme(legend.position = "top")
```

## Lets add our first annotation: text annotation example

```{r}
scatterplot +
  # first try using the geom_text
  geom_text(
    x = 35, 
    y = 217.5, 
    label = 'Important penguins', 
    fontface = 'bold', 
    size  = 4.5
  )
# as you can see the plot labels get all meshed up
# so lets fix the legend issue

scatterplot +
  # first try using the geom_text
  geom_text(
    x = 35, 
    y = 217.5, 
    label = 'Important penguins', 
    fontface = 'bold', 
    size  = 4.5, 
    show.legend = FALSE, 
    color = "black"
  )
# this fixes the issue but still the lable is little blurry lets see fix it using hte annotate and see the difference 

scatterplot +
  # first try using the geom_text
  annotate(
    'text', # we need to tell the annotate which geom we want to use here, its text. 
    x = 35, 
    y = 217.5, 
    label = 'Important penguins', 
    fontface = 'bold', 
    size  = 4.5, 
    # show.legend = FALSE, we needed to remove this
    color = "black"
  )
# now you can see that legend is more legible and not blurry
# also you can see that annotate and geom_text more or less the same code/information but annotate results in better annotatation. 


```

## Lets add our second annotation: rectangular annotation example

```{r}
# lets first do using geom_rect
scatterplot + 
   geom_text(
    x = 35, 
    y = 217.5, 
    label = 'Important penguins', 
    fontface = 'bold', 
    size  = 4.5, 
    show.legend = FALSE, 
    color = "black"
  ) + 
  
  geom_rect(
    xmin = 40, 
    xmax = 47, 
    ymin = 210, 
    ymax = 225, 
    alpha = 0.01, 
    fill = "grey40", 
    color = "black"
  )
# as you can the above code doesn't do the job neatly

```

```{r}
# so lets go back again to the annotate

scatterplot +
annotate(
    'text', # we need to tell the annotate which geom we want to use here, its text. 
    x = 35, 
    y = 217.5, 
    label = 'Important penguins', 
    fontface = 'bold', 
    size  = 4.5, 
    # show.legend = FALSE, we needed to remove this
    color = "black"
  ) + 
   
  annotate(
    'rect',
    xmin = 40, 
    xmax = 47, 
    ymin = 210, 
    ymax = 225, 
    alpha = 0.50, 
    fill = "grey40", 
    color = "black"
  ) + 
# now we can see that both text and rect annotation works better than using geom_text and geom_rect

# lets use arrow for the annotation as well 
  # checkout geom_curve() for arguments
annotate(
  'curve', 
  x = 32.5, 
  y = 219.5, 
  yend = 225, 
  xend = 39.75, 
  linewidth = 1, 
  curvature = -0.5,
  # you can try differnt value using +0.5 will give exactly opposite direction of the curve
  arrow = arrow(length = unit(0.5, 'cm'))
  # we can also use angle options in arrow check them out if required
  
)

```
